spring:
  datasource:
    url: jdbc:mysql://speedcheckdb.co7sofmnczsg.ap-northeast-2.rds.amazonaws.com:3306/selenium?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "!Xlfxndnjs21"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql:true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "tiltwoone@gmail.com"
    password: "umkecprmywchanes"
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 5000
      mail.smtp.starttls.enable: true

logging:
  level:
    org:
      hibernate:
        SQL: error

app:
  host: "https://speedcheck.til21.co.kr"

server:
  tomcat:
    max-http-form-post-size: 5MB
  port: 8888
