spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/timecheck
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql:true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: "email-smtp.ap-northeast-2.amazonaws.com"
    port: 25
    username: "AKIA2GA43SQ4GOATWNYE"
    password: "BD4tORbo7kfbayYI+Psl4s9Q3bI5w4PRgyKlajc3Bv6f"
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 5000
      mail.smtp.enable: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
app:
  host: "http://localhost:8888"

server:
  tomcat:
    max-http-form-post-size: 5MB

