spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/timecheck
    driver-class-name: org.h2.Driver
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql:true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug


